# Generated by Django 4.2.5 on 2023-09-16 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myuser',
            options={'verbose_name': 'İstifadəçi', 'verbose_name_plural': 'İstifadəçilər'},
        ),
        migrations.AddField(
            model_name='myuser',
            name='bio',
            field=models.TextField(default='', verbose_name='Bioqrafiya'),
        ),
    ]
